### ISSUE TITLE
Compass extension?

### ISSUE THREAD

**Issue by lolmaus** [designbyjake/sassline#18]
Hi!

A lot of people use Sass extensions via the ecosystem powered by RubyGems and Compass. I dare to presume that there are much more Compass users than libsass users.

Can you please distribute SassLine via RubyGems?

Basically, you need to add two files:

* `sassline.gemspec` ([example](https://github.com/lolmaus/breakpoint-slicer/blob/master/breakpoint-slicer.gemspec))
* `lib/sassline.rb` ([example](https://github.com/lolmaus/breakpoint-slicer/blob/master/lib/breakpoint-slicer.rb))

You will probably also have to rename `assets/sass/style.scss` to `assets/sass/sassline.scss`.

**Comment by jottr** [comment]
Hey @designbyjake are you still planning on implementing this?

**Comment by strarsis** [comment]
As workaround, you may use [sass-include-paths](https://www.npmjs.com/package/sass-include-paths) 
which will autogenerate the right include paths for you.
The array with the include paths can then be passed to gulp-ruby-sass for example.

With best regards

**Comment by designbyjake** [comment]
If this is still something that is desired then I welcome someone to create a PR. Closing this issue for now.
