### ISSUE TITLE
Use Bourbon to clean up code

### ISSUE THREAD

**Issue by ericyan** [designbyjake/sassline#22]
[Bourbon](http://bourbon.io/) is a Sass mixin library, which automatically handles vendor prefixes, modular scale, clearfix, etc. It's like Compass, but much more lightweight.

With Bourbon, we can make the code cleaner and more maintainable. That make it worthy to introduce a dependency for this project, in my opinion.

**Comment by mrtnbroder** [comment]
I disagree. The few mixins @designbyjake is using here are not worth adding the whole bourbon library as a dependency. If you use bourbon in your project then adjust the mixins to your needs. As there is https://github.com/postcss/autoprefixer, I wouldn't care about vendor prefixes though @designbyjake.

**Comment by designbyjake** [comment]
@ericyan @mrtnbroder I have some updates coming soon, hopefully — including using Autoprefixer so I’m going to close this. If you wanna use Bourbon too that’s cool but I’m not a fan  ¯\_(ツ)_/¯
