### ISSUE TITLE
Chrome REM bug

### ISSUE THREAD

**Issue by middric** [designbyjake/sassline#23]
A bug in Chrome causes font size inconsistency between refreshes. It only applies when rems are defined for the body font size. Switching the body to ems fixes the issue.

https://code.google.com/p/chromium/issues/detail?id=319623
and
https://code.google.com/p/chromium/issues/detail?id=362113

I've patched this by adding a $unit parameter (with 'rem' as the default value) to the fontsize mixin allowing me to pass in 'em' as the desired unit. Feels pretty hacky though.

**Comment by middric** [comment]
Also applies to the `line-height: 2rem` applied to the body (can just be em). https://github.com/designbyjake/sassline/blob/master/assets/sass/base/_typography.scss#L17-L19

**Comment by designbyjake** [comment]
@middric I’ve not seen this bug happen for quite some time now, do you have a link that replicates it?

**Comment by middric** [comment]
I'm afraid I dont. It seems to be a regression in chromium. The second ticket linked above has this occuring in stable 38+ and canary 41

**Comment by designbyjake** [comment]
I’m going to close this as I cannot reproduce the bug.
