### ISSUE TITLE
bower package not working

### ISSUE THREAD

**Issue by nevvkid** [designbyjake/sassline#30]
Hey. I just made a comment on the bower packaged pull request which was merged lately. 
The json doesn't seem to work as expected. 

See the comment on the Pull request here: https://github.com/designbyjake/sassline/pull/29

**Comment by mhumeSF** [comment]
Looks like [bower versioning](http://bower.io/docs/creating-packages/#version) requires version tagging to be x.y.z. On my fork I tagged the master branch as v2.1.0 and renamed the v2.0 to v2.0.0. I also updated the bower.json to include "main" and "ignore". But I don't think tags get pulled in a pull request so you'll have to retag 'em.

**Comment by mhumeSF** [comment]
@nevvkid Looks like version number have been added.

**Comment by designbyjake** [comment]
@nevvkid @mhumeSF can you confirm this is working now?

**Comment by mhumeSF** [comment]
@designbyjake Yup, it's workin' :smile:

**Comment by designbyjake** [comment]
:+1: Cheers @mhumeSF :)
